### ISSUE TITLE
Edit and redeploy external application

### ISSUE THREAD

**Issue by eugenesotnikov** [portainer/k8s#20]
I created application and i can edit and redeploy application created by me. But if application have tag external, i cann't edit and redeploy. But why? How to edit external application(with tag external)?
![image](https://user-images.githubusercontent.com/60689184/95098588-90457980-0737-11eb-89d7-4406bfc080fc.png)

**Comment by eugenesotnikov** [comment]
![image](https://user-images.githubusercontent.com/60689184/95098836-d7336f00-0737-11eb-9ecd-69d4e3f638c5.png)
![image](https://user-images.githubusercontent.com/60689184/95098876-e6b2b800-0737-11eb-92a0-8b855bb71e91.png)

**Comment by deviantony** [comment]
Closing as this one was re-opened in https://github.com/portainer/portainer/issues/4370
