### ISSUE TITLE
PV issue in version 2.0.0

### ISSUE THREAD

**Issue by drp2595** [portainer/k8s#39]
Hi Everyone, 
I was deploying the portainer 2.0.0 on kubernetes (k3s) cluster, I was facing issue with Persistent volume allocation after deploying it on cluster. so I added some content in yaml file to figure it out, I am extremely sorry, I dont have errors/issues in details cause I was working on client`s server and not able to take information from it. I am pasting the content for reference.

![image](https://user-images.githubusercontent.com/63572274/104559767-e4cb8f80-566a-11eb-951b-5cae134c7cce.png)

Edited:
I was facing two issues as mentioned below.

1.  I deployed Portainer on my Kubernetes cluster, I am trying to use API for my personal UI, whenever my Portainer or server is restarted then endpoint id is changing. due to change in endpoints I need to change API routes. (For this I used official yaml file and issue solved but use official yaml file made Portainer inaccessible. its issue 2)

so, While debugging I found that my environment wasn't ready for auto provisioning, so I need to add persistent volume to yaml file. I attached.

**Comment by deviantony** [comment]
Hey @drp2595 , can you give us more details on the error you're facing? Are you able to deploy Portainer?

**Comment by drp2595** [comment]
Yes, I am adding details, sorry for the inconvenience, cause server was not accessible for developers so, I requested the owner and I got the details. so, I edited the issue.

**Comment by drp2595** [comment]
as this issue resolved, I closed it.
