### ISSUE TITLE
Update the manifests to use the AlwaysPull policy

### ISSUE THREAD

**Issue by deviantony** [portainer/k8s#41]
We need to update our manifests to use the AlwaysPull image policy so that users can simply re-deploy the Portainer application and upgrade to the latest version.

**Comment by funkypenguin** [comment]
@deviantony this is already the case in recent versions of the chart : https://github.com/portainer/k8s/blob/master/charts/portainer/values.yaml#L18

**Comment by deviantony** [comment]
@funkypenguin Not for the manifests deployment though?

**Comment by deviantony** [comment]
Closing as this is already the case.
