### ISSUE TITLE
Error: cannot re-use a name that is still in use

### ISSUE THREAD

**Issue by doug62** [portainer/k8s#42]
helm uninstall portainer

helm repo add portainer https://portainer.github.io/k8s/
helm repo update

kubectl create namespace portainer
helm install portainer portainer/portainer -n portainer -f portainer-values.yml --debug

Yields:
Error: cannot re-use a name that is still in use 
helm.sh/helm/v3/pkg/action.(*Install).availableName
        /home/circleci/helm.sh/helm/pkg/action/install.go:435
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:181
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:242
main.newInstallCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374

**Comment by deviantony** [comment]
Hi @doug62, we're not able to reproduce this issue.

It could be related to  the fact that you need to remove the helm release properly (by specifying the `portainer` namespace):

`helm uninstall portainer -n portainer`

You could also try to remove the `portainer` namespace as well after that.

`kubectl delete namespace portainer`.
